apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: "RklDM2NVcHNoNnNQemRVdlpMRVRuWnJNM3FCZVU1SUc1dHk1T0llTDZWUWtveUhVbzVWT0pRUUo5OUJDQUNmaE1rNVhKM3czQUFBQUFDT0dDRE5u"
# Note: The value of OPENAI_API_KEY must be Base64-encoded.
# You can encode it using the following command:
# echo -n "your-actual-api-key" | base64
# it will return the encoded value which you can use in the secrets.yaml file.
